# Site settings
title: Rust Versions
description: > # this means to ignore newlines until "baseurl:"
  rust-community-versions provides helpful badges with versioning
  information to community resources, like blog posts.
baseurl: "/rust-community-versions"
# url: "http://steveklabnik.github.io"

# Build settings
markdown: kramdown
